/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaassignment;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static javaassignment.BookReg.getcon;
import static javaassignment.BookReg.s;
import javax.swing.JOptionPane;


/**
 *
 * @author Prasanga Fernando
 */
public class BookReg extends javax.swing.JFrame {

    /**
     * Creates new form BookReg
     */
    public BookReg() {
        initComponents();
    }
    static Connection c;
    static Statement s;
    static ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPublisher = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEdition = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 0));
        setMinimumSize(new java.awt.Dimension(700, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Book ISBN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 180, 64, 17);

        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });
        getContentPane().add(txtISBN);
        txtISBN.setBounds(150, 170, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Book Title");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 220, 80, 20);
        getContentPane().add(txtTitle);
        txtTitle.setBounds(150, 210, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Author");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 260, 60, 17);

        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });
        getContentPane().add(txtAuthor);
        txtAuthor.setBounds(150, 250, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Publisher");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 300, 60, 17);
        getContentPane().add(txtPublisher);
        txtPublisher.setBounds(150, 290, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Edition");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 180, 41, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Category");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 220, 57, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Released Year");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 250, 90, 17);
        getContentPane().add(txtEdition);
        txtEdition.setBounds(480, 170, 110, 30);
        getContentPane().add(txtCategory);
        txtCategory.setBounds(480, 210, 110, 30);
        getContentPane().add(txtYear);
        txtYear.setBounds(480, 250, 110, 30);

        btnRegister.setBackground(new java.awt.Color(46, 159, 30));
        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(570, 300, 100, 50);

        jPanel1.setBackground(new java.awt.Color(212, 201, 27));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(110, 60, 60));
        jLabel9.setText("Book Registration");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(282, 282, 282))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 100);

        Background.setBackground(new java.awt.Color(102, 102, 0));
        Background.setOpaque(true);
        getContentPane().add(Background);
        Background.setBounds(0, 0, 690, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    try{
        String sql = "INSERT INTO bookreg(ISBN,TITLE,AUTHOR,PUBLISHER,EDITION,CATEGORY,YEAR) "
         + "values('" +txtISBN.getText()+ "','" +txtTitle.getText()+ "','"+ txtAuthor.getText()+ "','"+ txtPublisher.getText()+ "','"+ txtEdition.getText()+ "','" +txtCategory.getText()+ "','" +txtYear.getText()+ "')";
        Updater(sql);
        JOptionPane.showMessageDialog(null, "Book inserted into the system successfully");
        }
        catch( Exception ex){
        JOptionPane.showMessageDialog(null, "Please fill the details");
        }
}
    
  
    
    public static Connection getcon() throws Exception{
        if (c==null) {
            Class.forName("com.mysql.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/javaassignment","root",null);
            
        }
        
        
      return c;  
    }
    

     public static void Updater(String query) throws Exception {
        
        if (c == null) {
            getcon();
        }
        
        if (s == null) {
            s = c.createStatement();
        }
        s.executeUpdate(query);
    }
    
   

 public static ResultSet Search(String query) throws SQLException, Exception {
        
        getcon();
        
        if (s == null) {
            s = c.createStatement();
        }
        
        rs = s.executeQuery(query);
        return rs;
    
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtEdition;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
